### ISSUE TITLE
'names' event returns only 10 nicks

### ISSUE THREAD

**Issue by GrantBartlett** [martynsmith/node-irc#414] opened 2015-10-11 10:51 UTC
Hi, this:
`Bot.addListener('names#channel', function (nicks) {
    console.log(nicks);
});
`
only returns 10 nicks, when there are at least 100+ available. Why would this be?

**Comment by Jnull** [comment] 2015-10-26 20:08
Working fine for me, try: 

```
var irc = require('irc');

var client = new irc.Client('irc.freenode.net',
  'Sabertooth', {
  channels: ['#freenode'],
  debug: false,
  userName: 'Woopie'
});

client.addListener('names#freenode', function (nicks) { 
	console.log(Object.keys(nicks).length)
}); 
```

**Comment by jirwin** [comment] 2016-03-27 17:14
I'm unable to reproduce this. Closing this for now.

**Closed by jirwin** 2016-03-27 17:14 UTC
